#!/usr/bin/bash

LIPV4="$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')"

VERME="\033[1;31m"
VERDE="\033[1;32m"
FIM="\033[0;00m"

# ASCII: https://www.twitchquotes.com/ascii-art-generator Width: 25
echo -e "\n⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo -e "⣿⣿⣿⠿⠿⠟⠛⠛⠛⠋⠉⠉⠉⠉⠀⠀⠀⠀⠀⢹⣿⣿⣿⣿⣿  ${VERDE}$USER${FIM}@${VERDE}$HOSTNAME${FIM}"
echo -e "⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿"
echo -e "⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣿⣷⣶⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿  ${VERME}DE${FIM}:\t\t\t $(echo $DESKTOP_SESSION)"
echo -e "⣿⣿⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿⣿  ${VERME}Term${FIM}:\t\t $(echo $TERM)"
echo -e "⣿⣿⡇⠀⠀⠀⠘⠛⠛⠛⠛⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿  ${VERME}IPv4 (Local)${FIM}:\t $(wget -q --spider "https://www.google.com/"; if [[ "$?" == "0" ]]; then echo -e "${LIPV4} ${VERDE}(Connected)${FIM}"; else echo -e "${LIPV4} ${VERME}(Not connected)${FIM}"; fi)"
echo -e "⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿  ${VERME}Kernel${FIM}:\t\t $(uname -r)"
echo -e "⣿⣿⡇⠀⠀⠀⣶⣶⣆⠀⠀⠀⠲⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿  ${VERME}Uptime${FIM}:\t\t $(echo $(uptime) | sed 's/^.\+up\ \+\([^,]*\).*/\1/g')"
echo -e "⣿⣿⡇⠀⠀⠀⢹⣿⣿⣆⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿  $(free -m | awk 'NR==2{printf "\033[1;31mMemory Usage\033[0m: \t %s / %sMB (%.2f%%)\n", $3,$2,$3*100/$2 }')"
echo -e "⣿⣿⣇⠀⠀⠀⠘⣿⣿⣿⣧⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿  ${VERME}Shell${FIM}:\t\t $(ps -u | awk '{print $11}' | sed -n 2p | tr -d '-')"
echo -e "⣿⣿⣿⠀⠀⠀⠀⢻⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿  ${VERME}OS${FIM}:\t\t\t $(cat /etc/os-release | head -n1 | tr -d '"','=','PRETTY_NAME')"
echo -e "⣿⣿⣿⣀⣀⡀⠀⠈⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⣿"
echo -e "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿\033[38;5;57m$(curl -s "https://type.fit/api/quotes" | jq '.[] | [.text]' | grep -e '"' | sort -R | head -n1 | tr -d '"')"${FIM}
exit 0
